### ISSUE TITLE
Percent

### ISSUE THREAD

**Issue by Resoluciones** [Snailz321/RandomCommand#1]
Hi!  Thanks for stopping by in the server.  Sorry, I had a problem at that time with the paperspigot build that makes it crash and restart, but now that is solved.

I have a problem with the plugin, maybe you can help me with it, as the plugin only chooses the first option, sometimes the second, but i have more than 40 options in the list and it always chooses the same.  When I put a higher percent on some of them, it always chooses the higher percent option, no matter how many times the plugin is called, it always choose the same options (the higher percent option or the first one in the list).

Can you let me know if this is a bug of the plugin or if this is generated by another reason?

Thanks!

**Comment by SnailzDev** [comment]
Sorry for the late response! If your still having this problem paste your config here.

**Comment by Resoluciones** [comment]
> 
> 
> Sorry for the late response! If your still having this problem paste your config here.

Hi!  I solved that problem long time ago! Thanks anyway! Regards.
