### ISSUE TITLE
Strange nosie

### ISSUE THREAD

**Issue by 0xC1A551C** [Snailz321/RandomCommand#2]
There is a strange noise when the /rc command is ran. Please have this configurable in the next recode or update. Thanks

**Comment by 0xC1A551C** [comment]
Also does not support color codes.

**Comment by SnailzDev** [comment]
The noise seems strange. Could I come on your server to test it out?

**Comment by 0xC1A551C** [comment]
The command in the plugin was causing noises (automatic update), so I disabled it. Not your plugins fault ill close.

Color codes started working.
